name: React Native CI/CD

on:
  push:
    branches:
      - main

env:
  JAVA_HOME: C:\Program Files\Java\jdk-11.0.12
  ANDROID_HOME: C:\Users\Deepa\AppData\Local\Android\Sdk
  PATH: ${{env.ANDROID_HOME}}\platform-tools;${{env.ANDROID_HOME}}\tools;%JAVA_HOME%\bin;%PATH%

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-
            $

      - name: Install dependencies
        run: npm install

      - name: Build Android APK
        run: npx react-native run-android --variant=release

      - name: Install APK on device
        run: adb install -r ./android/app/build/outputs/apk/release/app-release.apk
